// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/tournaments.proto

package tournaments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TournamentService_NewOrganizer_FullMethodName      = "/tournaments.TournamentService/NewOrganizer"
	TournamentService_NewTournament_FullMethodName     = "/tournaments.TournamentService/NewTournament"
	TournamentService_GetAllTorunaments_FullMethodName = "/tournaments.TournamentService/GetAllTorunaments"
)

// TournamentServiceClient is the client API for TournamentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TournamentServiceClient interface {
	NewOrganizer(ctx context.Context, in *NewOrganizerRequest, opts ...grpc.CallOption) (*Organizer, error)
	NewTournament(ctx context.Context, in *NewTournamentRequest, opts ...grpc.CallOption) (*Tournament, error)
	GetAllTorunaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TournamentList, error)
}

type tournamentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTournamentServiceClient(cc grpc.ClientConnInterface) TournamentServiceClient {
	return &tournamentServiceClient{cc}
}

func (c *tournamentServiceClient) NewOrganizer(ctx context.Context, in *NewOrganizerRequest, opts ...grpc.CallOption) (*Organizer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Organizer)
	err := c.cc.Invoke(ctx, TournamentService_NewOrganizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) NewTournament(ctx context.Context, in *NewTournamentRequest, opts ...grpc.CallOption) (*Tournament, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tournament)
	err := c.cc.Invoke(ctx, TournamentService_NewTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tournamentServiceClient) GetAllTorunaments(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TournamentList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TournamentList)
	err := c.cc.Invoke(ctx, TournamentService_GetAllTorunaments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TournamentServiceServer is the server API for TournamentService service.
// All implementations must embed UnimplementedTournamentServiceServer
// for forward compatibility.
type TournamentServiceServer interface {
	NewOrganizer(context.Context, *NewOrganizerRequest) (*Organizer, error)
	NewTournament(context.Context, *NewTournamentRequest) (*Tournament, error)
	GetAllTorunaments(context.Context, *Empty) (*TournamentList, error)
	mustEmbedUnimplementedTournamentServiceServer()
}

// UnimplementedTournamentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTournamentServiceServer struct{}

func (UnimplementedTournamentServiceServer) NewOrganizer(context.Context, *NewOrganizerRequest) (*Organizer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewOrganizer not implemented")
}
func (UnimplementedTournamentServiceServer) NewTournament(context.Context, *NewTournamentRequest) (*Tournament, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewTournament not implemented")
}
func (UnimplementedTournamentServiceServer) GetAllTorunaments(context.Context, *Empty) (*TournamentList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTorunaments not implemented")
}
func (UnimplementedTournamentServiceServer) mustEmbedUnimplementedTournamentServiceServer() {}
func (UnimplementedTournamentServiceServer) testEmbeddedByValue()                           {}

// UnsafeTournamentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TournamentServiceServer will
// result in compilation errors.
type UnsafeTournamentServiceServer interface {
	mustEmbedUnimplementedTournamentServiceServer()
}

func RegisterTournamentServiceServer(s grpc.ServiceRegistrar, srv TournamentServiceServer) {
	// If the following call pancis, it indicates UnimplementedTournamentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TournamentService_ServiceDesc, srv)
}

func _TournamentService_NewOrganizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewOrganizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).NewOrganizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_NewOrganizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).NewOrganizer(ctx, req.(*NewOrganizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_NewTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).NewTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_NewTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).NewTournament(ctx, req.(*NewTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TournamentService_GetAllTorunaments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TournamentServiceServer).GetAllTorunaments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TournamentService_GetAllTorunaments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TournamentServiceServer).GetAllTorunaments(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TournamentService_ServiceDesc is the grpc.ServiceDesc for TournamentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TournamentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tournaments.TournamentService",
	HandlerType: (*TournamentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewOrganizer",
			Handler:    _TournamentService_NewOrganizer_Handler,
		},
		{
			MethodName: "NewTournament",
			Handler:    _TournamentService_NewTournament_Handler,
		},
		{
			MethodName: "GetAllTorunaments",
			Handler:    _TournamentService_GetAllTorunaments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tournaments.proto",
}
